/**
 * 统一业务错误码（`architecture.md` §6.2）。
 * HTTP 状态映射由 API 层负责，本枚举仅标识业务语义。
 */
export const ErrorCode = {
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_ACCOUNT_DISABLED: "AUTH_ACCOUNT_DISABLED",
  AUTH_PASSWORD_CHANGE_REQUIRED: "AUTH_PASSWORD_CHANGE_REQUIRED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_CAPTCHA_REQUIRED: "AUTH_CAPTCHA_REQUIRED",
  AUTH_MFA_REQUIRED: "AUTH_MFA_REQUIRED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  UPLOAD_SESSION_INVALID: "UPLOAD_SESSION_INVALID",
  RESOURCE_LIMIT_EXCEEDED: "RESOURCE_LIMIT_EXCEEDED",
  OPERATION_NOT_ALLOWED: "OPERATION_NOT_ALLOWED",
  CONTEXT_LIMIT_EXCEEDED: "CONTEXT_LIMIT_EXCEEDED",
  TASK_INVALID_STATE: "TASK_INVALID_STATE",
  AI_PROVIDER_ERROR: "AI_PROVIDER_ERROR",
  AI_PROVIDER_TIMEOUT: "AI_PROVIDER_TIMEOUT",
  MEDIA_EXTRACT_FAILED: "MEDIA_EXTRACT_FAILED",
  MEDIA_PREPROCESS_FAILED: "MEDIA_PREPROCESS_FAILED",
  TASK_STALLED: "TASK_STALLED",
  AI_RATE_LIMITED: "AI_RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

/** 业务错误码字符串联合类型。 */
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** 错误码 → 建议 HTTP 状态（API Controller 映射用）。 */
export const ERROR_CODE_HTTP_STATUS: Readonly<Record<ErrorCode, number>> = {
  [ErrorCode.AUTH_UNAUTHORIZED]: 401,
  [ErrorCode.AUTH_FORBIDDEN]: 403,
  [ErrorCode.AUTH_ACCOUNT_DISABLED]: 403,
  [ErrorCode.AUTH_PASSWORD_CHANGE_REQUIRED]: 403,
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_CAPTCHA_REQUIRED]: 400,
  [ErrorCode.AUTH_MFA_REQUIRED]: 403,
  [ErrorCode.VALIDATION_FAILED]: 400,
  [ErrorCode.RESOURCE_NOT_FOUND]: 404,
  [ErrorCode.RESOURCE_CONFLICT]: 409,
  [ErrorCode.UPLOAD_SESSION_INVALID]: 400,
  [ErrorCode.RESOURCE_LIMIT_EXCEEDED]: 413,
  [ErrorCode.OPERATION_NOT_ALLOWED]: 422,
  [ErrorCode.CONTEXT_LIMIT_EXCEEDED]: 422,
  [ErrorCode.TASK_INVALID_STATE]: 422,
  [ErrorCode.AI_PROVIDER_ERROR]: 502,
  [ErrorCode.AI_PROVIDER_TIMEOUT]: 504,
  [ErrorCode.MEDIA_EXTRACT_FAILED]: 500,
  [ErrorCode.MEDIA_PREPROCESS_FAILED]: 500,
  [ErrorCode.TASK_STALLED]: 500,
  [ErrorCode.AI_RATE_LIMITED]: 429,
  [ErrorCode.INTERNAL_ERROR]: 500,
};

/**
 * 判断字符串是否为合法 {@link ErrorCode}。
 */
export function isErrorCode(value: string): value is ErrorCode {
  return Object.values(ErrorCode).includes(value as ErrorCode);
}
