import type { AuditLog, Customer, CustomerFeedback, DemoUser, FundTransaction, Rank, RiskCase, Settlement, Task } from "@/types/demo";

export const demoRanks: Rank[] = [
  { code: "L1A", name: "L1A 初级 A", settlementBasisPoints: 6000, sortOrder: 1 },
  { code: "L1B", name: "L1B 初级 B", settlementBasisPoints: 6500, sortOrder: 2 },
  { code: "L1C", name: "L1C 初级 C", settlementBasisPoints: 7000, sortOrder: 3 },
  { code: "L2A", name: "L2A 中级 A", settlementBasisPoints: 7500, sortOrder: 4 },
  { code: "L2B", name: "L2B 中级 B", settlementBasisPoints: 8000, sortOrder: 5 },
  { code: "L2C", name: "L2C 中级 C", settlementBasisPoints: 8500, sortOrder: 6 },
  { code: "L3A", name: "L3A 高级 A", settlementBasisPoints: 9000, sortOrder: 7 },
  { code: "L3B", name: "L3B 高级 B", settlementBasisPoints: 9500, sortOrder: 8 },
  { code: "L3C", name: "L3C 高级 C", settlementBasisPoints: 10000, sortOrder: 9 },
];

export const demoUsers: DemoUser[] = [
  {
    id: "u-admin",
    username: "admin",
    displayName: "系统管理员",
    role: "system_admin",
    password: "111111",
    mustChangePassword: true,
    status: "active",
  },
  {
    id: "u-source",
    username: "source01",
    displayName: "周律师",
    role: "source_lawyer",
    password: "111111",
    mustChangePassword: true,
    status: "active",
  },
  {
    id: "u-firm",
    username: "firm01",
    displayName: "律所管理员",
    role: "firm_admin",
    password: "111111",
    mustChangePassword: true,
    status: "active",
  },
  {
    id: "u-director",
    username: "director01",
    displayName: "管委会主任",
    role: "director",
    password: "111111",
    mustChangePassword: true,
    status: "active",
  },
  {
    id: "u-source-2",
    username: "source02",
    displayName: "陈合伙人",
    role: "source_lawyer",
    password: "111111",
    mustChangePassword: true,
    status: "active",
  },
  {
    id: "u-handler",
    username: "lawyer01",
    displayName: "林律师",
    role: "handling_lawyer",
    rankCode: "L2B",
    password: "111111",
    mustChangePassword: true,
    status: "active",
  },
  {
    id: "u-junior",
    username: "lawyer02",
    displayName: "吴青年律师",
    role: "handling_lawyer",
    rankCode: "L1C",
    password: "111111",
    mustChangePassword: true,
    status: "active",
  },
  {
    id: "u-senior",
    username: "lawyer03",
    displayName: "赵高级律师",
    role: "handling_lawyer",
    rankCode: "L3A",
    password: "111111",
    mustChangePassword: true,
    status: "active",
  },
  {
    id: "u-finance",
    username: "finance01",
    displayName: "财务负责人",
    role: "finance",
    password: "111111",
    mustChangePassword: true,
    status: "active",
  },
];

export const demoCustomers: Customer[] = [
  {
    id: "c-001",
    name: "东辰科技有限公司",
    contactName: "王总",
    phone: "13800000000",
    source: "律师录入",
  },
  {
    id: "c-002",
    name: "星河智能装备有限公司",
    contactName: "李总",
    phone: "13900000000",
    source: "渠道推荐",
  },
  {
    id: "c-003",
    name: "宏远建设集团",
    contactName: "赵经理",
    phone: "13700000000",
    source: "合伙人转介绍",
  },
  {
    id: "c-004",
    name: "安澜医疗科技",
    contactName: "许女士",
    phone: "13600000000",
    source: "官网咨询",
  },
];

export const demoTasks: Task[] = [
  {
    id: "t-001",
    title: "股权激励协议审查",
    customerId: "c-002",
    description: "审查核心员工股权激励协议，标注回购、竞业限制和税务风险。",
    taskType: "合同审查",
    amountCents: 900000,
    minRankCode: "L1C",
    sourceLawyerId: "u-source-2",
    status: "open",
    dueAt: "2026-07-05",
    portalToken: "LEXOS-DEMO-001",
  },
  {
    id: "t-002",
    title: "劳动争议证据梳理",
    customerId: "c-003",
    description: "整理离职争议证据、聊天记录和工资流水，形成仲裁前材料清单。",
    taskType: "劳动争议",
    amountCents: 800000,
    minRankCode: "L1A",
    sourceLawyerId: "u-source",
    assignedLawyerId: "u-junior",
    status: "claimed",
    dueAt: "2026-06-28",
    portalToken: "LEXOS-DEMO-002",
  },
  {
    id: "t-003",
    title: "买卖合同纠纷诉前方案",
    customerId: "c-001",
    description: "围绕逾期付款、质量抗辩和保全可能性形成诉前策略。",
    taskType: "诉前方案",
    amountCents: 1500000,
    minRankCode: "L2A",
    sourceLawyerId: "u-source",
    assignedLawyerId: "u-handler",
    status: "submitted",
    dueAt: "2026-06-25",
    portalToken: "LEXOS-DEMO-003",
    submittedTitle: "诉前策略与证据清单",
    submittedContent: "已完成诉前风险研判、保全建议和证据补强清单，等待发起人验收。",
    externalUrl: "https://example.com/lexos/demo/pre-litigation-plan",
    reviewLawyerId: "u-director",
    reviewRequired: true,
    reviewStatus: "pending",
  },
  {
    id: "t-004",
    title: "民商事一审代理材料准备",
    customerId: "c-001",
    description: "完成一审起诉材料、证据目录和立案前审查。",
    taskType: "诉讼任务",
    amountCents: 1200000,
    minRankCode: "L2A",
    sourceLawyerId: "u-source",
    assignedLawyerId: "u-handler",
    status: "approved",
    dueAt: "2026-07-01",
    portalToken: "LEXOS-DEMO-004",
    submittedTitle: "一审立案材料包",
    submittedContent: "起诉状、证据目录和授权材料已整理完成，客户可在大屏确认接收。",
    externalUrl: "https://example.com/lexos/demo/first-instance-package",
    approvedAt: "2026-06-01 09:30",
    reviewComment: "材料结构完整，诉讼风险提示充分。",
    reviewLawyerId: "u-director",
    reviewRequired: true,
    reviewStatus: "approved",
    reviewedAt: "2026-06-08 08:50",
    sourceReviewScore: 9,
    sourceReviewComment: "材料完整度高，立案风险提示清楚。",
    sourceReviewedAt: "2026-06-08 09:30",
    caseResultScore: 8,
    caseResultSummary: "已满足客户确认前的立案材料准备要求。",
  },
  {
    id: "t-005",
    title: "数据合规专项法律意见",
    customerId: "c-002",
    description: "针对客户数据出境、员工权限和供应商系统接入形成合规意见。",
    taskType: "专项法律意见",
    amountCents: 2800000,
    minRankCode: "L3A",
    sourceLawyerId: "u-source-2",
    assignedLawyerId: "u-senior",
    status: "settlement_pending",
    dueAt: "2026-06-20",
    portalToken: "LEXOS-DEMO-005",
    submittedTitle: "数据合规专项意见书",
    submittedContent: "已完成数据流向、权限矩阵和整改建议，客户已确认接收。",
    externalUrl: "https://example.com/lexos/demo/data-compliance-opinion",
    approvedAt: "2026-06-06 14:20",
    sourceReviewScore: 9,
    sourceReviewComment: "专项意见结构清晰，整改建议可直接执行。",
    sourceReviewedAt: "2026-06-06 14:20",
    caseResultScore: 9,
    caseResultSummary: "合规整改路径明确，客户已安排内部落地。",
    customerConfirmedAt: "2026-06-07 10:15",
  },
  {
    id: "t-006",
    title: "建设工程付款争议谈判包",
    customerId: "c-003",
    description: "围绕工程款支付、签证单和结算审计形成谈判材料。",
    taskType: "争议解决",
    amountCents: 3600000,
    minRankCode: "L2B",
    sourceLawyerId: "u-source",
    assignedLawyerId: "u-handler",
    status: "settled",
    dueAt: "2026-06-18",
    portalToken: "LEXOS-DEMO-006",
    submittedTitle: "工程款谈判材料包",
    submittedContent: "已形成付款节点表、争议金额测算和谈判底线建议。",
    externalUrl: "https://example.com/lexos/demo/construction-negotiation",
    approvedAt: "2026-06-05 16:40",
    sourceReviewScore: 10,
    sourceReviewComment: "争议金额测算扎实，谈判底线明确。",
    sourceReviewedAt: "2026-06-05 16:40",
    caseResultScore: 9,
    caseResultSummary: "谈判材料已用于客户与相对方沟通。",
    customerConfirmedAt: "2026-06-06 11:00",
  },
  {
    id: "t-007",
    title: "医疗器械经销合同风险排查",
    customerId: "c-004",
    description: "原计划审查经销合同独家代理条款，后因客户业务安排取消。",
    taskType: "合同审查",
    amountCents: 600000,
    minRankCode: "L2B",
    sourceLawyerId: "u-source-2",
    assignedLawyerId: "u-handler",
    status: "cancelled",
    dueAt: "2026-06-22",
    portalToken: "LEXOS-DEMO-007",
  },
  {
    id: "t-008",
    title: "企业并购尽调清单复核",
    customerId: "c-004",
    description: "复核并购项目核心尽调清单，重点关注股权、资产、劳动用工和重大合同。",
    taskType: "并购尽调",
    amountCents: 4200000,
    minRankCode: "L3A",
    sourceLawyerId: "u-source-2",
    status: "open",
    dueAt: "2026-07-08",
    portalToken: "LEXOS-DEMO-008",
  },
  {
    id: "t-009",
    title: "劳动合同解除谈判纪要",
    customerId: "c-003",
    description: "整理劳动合同解除谈判纪要、补偿测算和风险提示。",
    taskType: "劳动争议",
    amountCents: 700000,
    minRankCode: "L1A",
    sourceLawyerId: "u-source",
    assignedLawyerId: "u-junior",
    status: "settled",
    dueAt: "2026-06-15",
    portalToken: "LEXOS-DEMO-009",
    submittedTitle: "解除谈判纪要",
    submittedContent: "已完成补偿测算、沟通纪要和风险提示，客户已确认。",
    externalUrl: "https://example.com/lexos/demo/labor-negotiation",
    approvedAt: "2026-06-04 15:00",
    sourceReviewScore: 8,
    sourceReviewComment: "补偿测算完整，沟通纪要还可继续模板化。",
    sourceReviewedAt: "2026-06-04 15:00",
    caseResultScore: 8,
    caseResultSummary: "客户已按谈判纪要完成后续沟通。",
    customerConfirmedAt: "2026-06-05 09:35",
  },
];

export const demoSettlements: Settlement[] = [
  {
    id: "s-001",
    taskId: "t-005",
    taskTitle: "数据合规专项法律意见",
    lawyerId: "u-senior",
    lawyerName: "赵高级律师",
    rankCode: "L3A",
    taskAmountCents: 2800000,
    settlementBasisPoints: 9000,
    settlementAmountCents: 2520000,
    payableAmountCents: 2520000,
    status: "pending",
    generatedAt: "2026-06-07T10:15:00.000Z",
  },
  {
    id: "s-002",
    taskId: "t-006",
    taskTitle: "建设工程付款争议谈判包",
    lawyerId: "u-handler",
    lawyerName: "林律师",
    rankCode: "L2B",
    taskAmountCents: 3600000,
    settlementBasisPoints: 8000,
    settlementAmountCents: 2880000,
    payableAmountCents: 2880000,
    status: "confirmed",
    generatedAt: "2026-06-06T11:00:00.000Z",
    confirmedAt: "2026-06-08T09:30:00.000Z",
  },
  {
    id: "s-003",
    taskId: "t-009",
    taskTitle: "劳动合同解除谈判纪要",
    lawyerId: "u-junior",
    lawyerName: "吴青年律师",
    rankCode: "L1C",
    taskAmountCents: 700000,
    settlementBasisPoints: 7000,
    settlementAmountCents: 490000,
    payableAmountCents: 490000,
    status: "confirmed",
    generatedAt: "2026-06-05T09:35:00.000Z",
    confirmedAt: "2026-06-08T16:20:00.000Z",
  },
];

export const demoFeedback: CustomerFeedback[] = [
  {
    taskId: "t-005",
    score: 9,
    comment: "交付清晰，整改建议可以直接安排内部执行。",
    confirmedAt: "2026-06-07 10:15",
  },
  {
    taskId: "t-006",
    score: 10,
    comment: "谈判材料结构清楚，财务测算很有帮助。",
    confirmedAt: "2026-06-06 11:00",
  },
  {
    taskId: "t-009",
    score: 8,
    comment: "补偿测算清楚，后续希望增加模板化沟通记录。",
    confirmedAt: "2026-06-05 09:35",
  },
];

export const demoFundTransactions: FundTransaction[] = [];

export const demoRiskCases: RiskCase[] = [
  {
    id: "r-001",
    createdAt: "2026-06-08 10:20",
    customerId: "c-003",
    customerName: "海岳制造集团",
    description: "客户对交付材料的证据引用完整性提出异议，主任需要跟进复核。",
    rawCreatedAt: "2026-06-08T10:20:00.000Z",
    rawUpdatedAt: "2026-06-08T11:00:00.000Z",
    ownerUserId: "u-director",
    ownerName: "周主任",
    reportedByUserId: "u-source",
    reporterName: "王源律师",
    severity: "high",
    source: "customer_complaint",
    status: "in_review",
    taskId: "t-003",
    taskTitle: "买卖合同纠纷证据梳理",
    title: "客户投诉：证据引用完整性异议",
    updatedAt: "2026-06-08 11:00",
  },
  {
    id: "r-002",
    createdAt: "2026-06-05 09:40",
    customerId: "c-004",
    customerName: "星河人力资源",
    description: "客户评分 6 分，低于当前低分风控阈值，需要回看交付说明和沟通记录。",
    rawCreatedAt: "2026-06-05T09:40:00.000Z",
    severity: "medium",
    source: "low_score",
    status: "open",
    taskId: "t-006",
    taskTitle: "劳动仲裁补偿测算",
    title: "客户评分 6 分：劳动仲裁补偿测算",
  },
  {
    id: "r-004",
    createdAt: "2026-06-08 15:30",
    committeeDecidedAt: "2026-06-08T17:00:00.000Z",
    committeeDecidedByUserId: "u-director",
    committeeDeciderName: "周主任",
    committeeDecision: "deduction",
    committeeDecisionNote: "交付说明补充不充分，按中级风险扣减并转入公共风险储备金。",
    committeeDeductionBasisPoints: 1500,
    customerId: "c-002",
    customerName: "蓝湖资本",
    defendedAt: "2026-06-08T16:30:00.000Z",
    defenseStatement: "已补充数据合规整改说明和客户沟通记录，请委员会复核扣减比例。",
    description: "待结算任务进入客户补充说明复核，结算金额需冻结至风控办结。",
    rawCreatedAt: "2026-06-08T15:30:00.000Z",
    rawUpdatedAt: "2026-06-08T17:00:00.000Z",
    ownerUserId: "u-director",
    ownerName: "周主任",
    severity: "medium",
    source: "manual",
    status: "in_review",
    taskId: "t-005",
    taskTitle: "数据合规专项法律意见",
    title: "扣减裁决：结算前补充说明复核",
    updatedAt: "2026-06-08 17:00",
  },
  {
    id: "r-005",
    createdAt: "2026-06-09 09:10",
    customerId: "c-003",
    customerName: "宏远建设集团",
    description: "客户要求说明劳动合同解除谈判纪要中的补偿测算假设，承办律师需在 48 小时内提交答辩说明。",
    rawCreatedAt: "2026-06-09T09:10:00.000Z",
    severity: "medium",
    source: "manual",
    status: "open",
    taskAssignedLawyerId: "u-junior",
    taskId: "t-009",
    taskTitle: "劳动合同解除谈判纪要",
    title: "承办律师答辩：补偿测算假设说明",
  },
  {
    id: "r-006",
    createdAt: "2026-06-09 10:05",
    customerId: "c-004",
    customerName: "星河人力资源",
    defendedAt: "2026-06-09T10:30:00.000Z",
    defenseStatement: "已补充补偿测算依据、客户沟通纪要和后续整改计划，请委员会复核。",
    description: "承办律师已提交答辩，等待委员会形成第一版裁决记录。",
    rawCreatedAt: "2026-06-09T10:05:00.000Z",
    rawUpdatedAt: "2026-06-09T10:30:00.000Z",
    severity: "high",
    source: "manual",
    status: "in_review",
    taskAssignedLawyerId: "u-handler",
    taskId: "t-006",
    taskTitle: "建设工程付款争议谈判包",
    title: "委员会裁决：补偿测算复核",
    updatedAt: "2026-06-09 10:30",
  },
  {
    id: "r-003",
    createdAt: "2026-06-03 14:15",
    customerId: "c-002",
    customerName: "蓝湖资本",
    description: "人工登记的历史提醒，已完成交付复盘，无需继续跟进。",
    rawCreatedAt: "2026-06-03T14:15:00.000Z",
    rawUpdatedAt: "2026-06-04T11:00:00.000Z",
    resolutionNote: "主任已复核交付材料，确认仅需补充客户沟通记录归档。",
    reportedByUserId: "u-admin",
    reporterName: "系统管理员",
    resolvedAt: "2026-06-04T11:00:00.000Z",
    severity: "low",
    source: "manual",
    status: "resolved",
    taskId: "t-005",
    taskTitle: "数据合规专项法律意见",
    title: "交付复盘提醒",
    updatedAt: "2026-06-04 11:00",
  },
];

export const demoAuditLogs: AuditLog[] = [
  {
    id: "a-012",
    actor: "律所管理员",
    action: "更新系统参数",
    actionCode: "system_settings.update",
    entity: "system_settings/default_page_size",
    entityType: "system_settings",
    createdAt: "2026-06-08 10:05",
    rawCreatedAt: "2026-06-08T02:05:00.000Z",
  },
  {
    id: "a-011",
    actor: "系统管理员",
    action: "创建客户 安澜医疗科技",
    actionCode: "customers.create",
    entity: "customers/c-004",
    entityType: "customers",
    createdAt: "2026-06-08 10:00",
    rawCreatedAt: "2026-06-08T02:00:00.000Z",
  },
  {
    id: "a-010b",
    actor: "陈合伙人",
    action: "取消任务 医疗器械经销合同风险排查",
    actionCode: "tasks.cancel",
    entity: "tasks/t-007",
    entityType: "tasks",
    createdAt: "2026-06-08 09:59",
    rawCreatedAt: "2026-06-08T01:59:00.000Z",
  },
  {
    id: "a-010",
    actor: "系统管理员",
    action: "创建用户 吴青年律师",
    actionCode: "users.create",
    entity: "users/u-junior",
    entityType: "users",
    createdAt: "2026-06-08 09:58",
    rawCreatedAt: "2026-06-08T01:58:00.000Z",
  },
  {
    id: "a-009",
    actor: "林律师",
    action: "首次登录修改密码",
    actionCode: "auth.change_password",
    entity: "auth/u-handler",
    entityType: "auth",
    createdAt: "2026-06-08 09:54",
    rawCreatedAt: "2026-06-08T01:54:00.000Z",
  },
  {
    id: "a-008",
    actor: "系统",
    action: "登录失败 lawyer02",
    actionCode: "auth.login_failed",
    entity: "auth/u-junior",
    entityType: "auth",
    createdAt: "2026-06-08 09:50",
    rawCreatedAt: "2026-06-08T01:50:00.000Z",
  },
  {
    id: "a-007",
    actor: "财务负责人",
    action: "确认结算 建设工程付款争议谈判包",
    actionCode: "settlements.confirm",
    entity: "settlements/s-002",
    entityType: "settlements",
    createdAt: "2026-06-08 09:45",
    rawCreatedAt: "2026-06-08T01:45:00.000Z",
  },
  {
    id: "a-006",
    actor: "客户",
    action: "确认接收并评分 数据合规专项法律意见",
    actionCode: "customer_portal.feedback",
    entity: "customer_portal/t-005",
    entityType: "customer_portal",
    createdAt: "2026-06-07 10:15",
    rawCreatedAt: "2026-06-07T02:15:00.000Z",
  },
  {
    id: "a-005",
    actor: "陈合伙人",
    action: "验收任务 数据合规专项法律意见",
    actionCode: "tasks.approve",
    entity: "tasks/t-005",
    entityType: "tasks",
    createdAt: "2026-06-06 14:20",
    rawCreatedAt: "2026-06-06T06:20:00.000Z",
  },
  {
    id: "a-004",
    actor: "林律师",
    action: "提交成果 买卖合同纠纷诉前方案",
    actionCode: "tasks.submit",
    entity: "tasks/t-003",
    entityType: "tasks",
    createdAt: "2026-06-06 11:20",
    rawCreatedAt: "2026-06-06T03:20:00.000Z",
  },
  {
    id: "a-003",
    actor: "吴青年律师",
    action: "抢单 劳动争议证据梳理",
    actionCode: "tasks.claim",
    entity: "tasks/t-002",
    entityType: "tasks",
    createdAt: "2026-06-06 10:40",
    rawCreatedAt: "2026-06-06T02:40:00.000Z",
  },
  {
    id: "a-002",
    actor: "周律师",
    action: "发布任务 民商事一审代理材料准备",
    actionCode: "tasks.create",
    entity: "tasks/t-004",
    entityType: "tasks",
    createdAt: "2026-06-06 10:10",
    rawCreatedAt: "2026-06-06T02:10:00.000Z",
  },
  {
    id: "a-001",
    actor: "系统",
    action: "初始化 demo 数据",
    actionCode: "system.demo_seed",
    entity: "workspace",
    entityType: "workspace",
    createdAt: "2026-06-06 10:00",
    rawCreatedAt: "2026-06-06T10:00:00.000Z",
  },
];
