-- =============================================================================
-- LexOS M10-G — SOP AI 功能点映射种子模板
-- =============================================================================
--
-- 四 SOP feature_key 须指向已存在 ai_model_credentials.id 的幂等 INSERT。
-- 若默认 fallback 模型不存在，跳过 INSERT（由 run-sop-ai-mappings-seed CLI 处理）。
--
-- feature_key 值（与 public.ai_feature_key 枚举一致）：
--   sop.fact_extract
--   sop.strategy_gen
--   sop.deep_research
--   sop.visual_charting
--
-- 幂等模板（需替换 :default_model_id 为实际 UUID）：
--
-- INSERT INTO public.ai_feature_model_mappings (feature_key, primary_model_id)
-- VALUES
--   ('sop.fact_extract'::public.ai_feature_key, :default_model_id),
--   ('sop.strategy_gen'::public.ai_feature_key, :default_model_id),
--   ('sop.deep_research'::public.ai_feature_key, :default_model_id),
--   ('sop.visual_charting'::public.ai_feature_key, :default_model_id)
-- ON CONFLICT (feature_key) DO NOTHING;
-- =============================================================================
