import type {
  Database,
  TablesInsert,
  TablesUpdate,
} from './database.types'

type PublicTables = Database['public']['Tables']

// ---------------------------------------------------------------------------
// 基准实体别名（从 Database Row 派生）
// ---------------------------------------------------------------------------

export type Profile = PublicTables['profiles']['Row']
export type AiModelConfig = PublicTables['ai_model_configs']['Row']
export type LegalSop = PublicTables['legal_sops']['Row']
export type LegalTask = PublicTables['legal_tasks']['Row']
export type AuditLog = PublicTables['audit_logs']['Row']

// ---------------------------------------------------------------------------
// 跨境与状态边界约束
// ---------------------------------------------------------------------------

/** 案件/业务数据所属法域标识 */
export type DataRegion = 'mainland' | 'hongkong'

/** 任务工作流状态 */
export type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'cancelled'

/** 风险控制校验状态（严禁使用 quality_control 命名） */
export type RiskControlStatus = 'unverified' | 'passed' | 'failed'

/** 带法域边界约束的 SOP 视图类型（API 层响应推导用） */
export type LegalSopRegional = Omit<LegalSop, 'data_region'> & {
  data_region: DataRegion
}

/** 带状态边界约束的任务视图类型（API 层响应推导用） */
export type LegalTaskWithStatus = Omit<
  LegalTask,
  'status' | 'risk_control_status'
> & {
  status: TaskStatus
  risk_control_status: RiskControlStatus
}

type AutoGeneratedFields = 'id' | 'created_at' | 'updated_at'

// ---------------------------------------------------------------------------
// API Request Payload（创建 / 更新载荷）
// ---------------------------------------------------------------------------

export type CreateSopRequest = Omit<
  TablesInsert<'legal_sops'>,
  AutoGeneratedFields | 'data_region'
> & {
  data_region: DataRegion
}

export type UpdateSopRequest = Omit<
  TablesUpdate<'legal_sops'>,
  AutoGeneratedFields | 'data_region'
> & {
  data_region?: DataRegion
}

export type CreateTaskRequest = Omit<
  TablesInsert<'legal_tasks'>,
  AutoGeneratedFields | 'status' | 'risk_control_status'
> & {
  status?: TaskStatus
  risk_control_status?: RiskControlStatus
}

export type UpdateTaskRequest = Omit<
  TablesUpdate<'legal_tasks'>,
  AutoGeneratedFields | 'status' | 'risk_control_status'
> & {
  status?: TaskStatus
  risk_control_status?: RiskControlStatus
}

/** created_by 由服务端从 auth.uid() 注入，前端不得伪造 */
export type CreateAiConfigPayload = Omit<
  TablesInsert<'ai_model_configs'>,
  AutoGeneratedFields | 'created_by'
>

export type UpdateAiConfigPayload = Omit<
  TablesUpdate<'ai_model_configs'>,
  AutoGeneratedFields | 'created_by'
>

// ---------------------------------------------------------------------------
// 标准 API 响应包装器
// ---------------------------------------------------------------------------

export interface ApiResponse<T> {
  success: boolean
  data: T | null
  error: {
    code: string
    message: string
    details?: string
  } | null
}
